version: '3'

# network must exist, another create: docker network create -d bridge spring1_network
# or set external DB
networks:
    spring1_network:
        external: true

services:
    openjdk:
        container_name: maintenance
        build: ./
        restart: unless-stopped
        networks:
            - spring1_network
        external_links:
            - pgsql_for_learning:postgres
        environment:
            POSTGRES_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            server.port: 8080
        ports:
            - ${APP_PORT}:8080